/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conexion;
import java.awt.Color;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author alfre
 */
public class Plomero extends javax.swing.JFrame {

    Conexion oCnx;
    DefaultTableModel modelo;
    TableColumnModel modeloColumna;
    
    /**
     * Creates new form Plomero
     */
    public Plomero() {
        initComponents();
        Color color = new Color(255,255,255);
        getContentPane().setBackground(color);
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel)this.jTableRegistro.getModel();
        this.jTableRegistro.setShowHorizontalLines(true);
        this.jTableRegistro.setShowVerticalLines(true);
        oCnx = new Conexion();
        oCnx.mostrarPlomero(jTableRegistro);
        modeloColumna = jTableRegistro.getColumnModel();
        modeloColumna.getColumn(0).setPreferredWidth(50);
        modeloColumna.getColumn(1).setPreferredWidth(90);
        modeloColumna.getColumn(2).setPreferredWidth(90);
        modeloColumna.getColumn(3).setPreferredWidth(90);
        modeloColumna.getColumn(4).setPreferredWidth(90);
        modeloColumna.getColumn(5).setPreferredWidth(30);
        modeloColumna.getColumn(6).setPreferredWidth(90);
        modeloColumna.getColumn(7).setPreferredWidth(40);
        modeloColumna.getColumn(8).setPreferredWidth(154);
    }
    
    char [] abc = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'};
    
    String [] nombres = {"Jose", "Alejandro", "Angel", "David", "Alfredo", "Javier", "Jorge"
                        ,"Gael", "Jaime", "Alberto", "Carlos", "Marcos", "Francisco", "Alfonso"
                        ,"Victor", "Jaciel", "Juan", "Fernando", "Diego", "Jesus", "Cesar"};
    
    String [] Aps = {"Gaytan", "Lopez", "Avalos", "Carrillo", "Puentes", "Vargas", "Cortinas"
                        ,"Luevanos", "Favela", "Saucedo", "Anguiano", "Garcia", "Esquivel", "Silos"
                        ,"Ortiz", "Suarez", "Estrada", "Hernandez", "Avitia", "Diaz", "Rivera"};
    
    Random random = new Random();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        jButtonMostrar = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jTextNomb2 = new javax.swing.JTextField();
        L8 = new javax.swing.JLabel();
        jButtonBaja = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistro = new javax.swing.JTable();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        jTextApMaterno = new javax.swing.JTextField();
        jTextCurp = new javax.swing.JTextField();
        jTextNomb1 = new javax.swing.JTextField();
        jTextApPaterno = new javax.swing.JTextField();
        L9 = new javax.swing.JLabel();
        jButtonMenu = new javax.swing.JButton();
        jButtonAleatorios = new javax.swing.JButton();
        jSpinnerDia = new javax.swing.JSpinner();
        jSpinnerAño = new javax.swing.JSpinner();
        jComboMes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        L6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 13)); // NOI18N
        L6.setForeground(new java.awt.Color(51, 51, 51));
        L6.setText("CORREO ELECTRÓNICO:");

        L7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 13)); // NOI18N
        L7.setForeground(new java.awt.Color(51, 51, 51));
        L7.setText("APELLIDO PATERNO:");

        jButtonMostrar.setBackground(new java.awt.Color(102, 0, 153));
        jButtonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonMostrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMostrar.setText("MOSTRAR");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonAlta.setBackground(new java.awt.Color(0, 102, 0));
        jButtonAlta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAlta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlta.setText("ALTA");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jTextNomb2.setBackground(new java.awt.Color(204, 204, 255));
        jTextNomb2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextNomb2.setPreferredSize(new java.awt.Dimension(70, 22));

        L8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 13)); // NOI18N
        L8.setForeground(new java.awt.Color(51, 51, 51));
        L8.setText("APELLIDO MATERNO:");

        jButtonBaja.setBackground(new java.awt.Color(153, 0, 0));
        jButtonBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBaja.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBaja.setText("BAJA");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonModificar.setBackground(new java.awt.Color(102, 0, 153));
        jButtonModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jTableRegistro.setBackground(new java.awt.Color(204, 204, 255));
        jTableRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CURP", "1ER NOMBRE", "2DO NOMBRE", "AP PATERNO", "AP MATERNO", "DIA", "MES", "AÑO", "CORREO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRegistro.getTableHeader().setReorderingAllowed(false);
        jTableRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRegistroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRegistro);

        L4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 13)); // NOI18N
        L4.setForeground(new java.awt.Color(51, 51, 51));
        L4.setText("PRIMER NOMBRE:");

        L3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 13)); // NOI18N
        L3.setForeground(new java.awt.Color(51, 51, 51));
        L3.setText("CURP:");

        L5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 13)); // NOI18N
        L5.setForeground(new java.awt.Color(51, 51, 51));
        L5.setText("SEGUNDO NOMBRE:");

        L1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        L1.setForeground(new java.awt.Color(102, 0, 153));
        L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L1.setText("REGISTRO DE PLOMEROS");
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
        });

        L2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        L2.setForeground(new java.awt.Color(51, 51, 51));
        L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2.setText("____________________________________________________________________");
        L2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextCorreo.setBackground(new java.awt.Color(204, 204, 255));
        jTextCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextCorreo.setPreferredSize(new java.awt.Dimension(70, 22));

        jTextApMaterno.setBackground(new java.awt.Color(204, 204, 255));
        jTextApMaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextApMaterno.setPreferredSize(new java.awt.Dimension(70, 22));

        jTextCurp.setBackground(new java.awt.Color(204, 204, 255));
        jTextCurp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextCurp.setPreferredSize(new java.awt.Dimension(70, 22));

        jTextNomb1.setBackground(new java.awt.Color(204, 204, 255));
        jTextNomb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextNomb1.setPreferredSize(new java.awt.Dimension(70, 22));

        jTextApPaterno.setBackground(new java.awt.Color(204, 204, 255));
        jTextApPaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextApPaterno.setPreferredSize(new java.awt.Dimension(70, 22));

        L9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 13)); // NOI18N
        L9.setForeground(new java.awt.Color(51, 51, 51));
        L9.setText("FECHA DE NACIMIENTO:");

        jButtonMenu.setBackground(new java.awt.Color(102, 0, 153));
        jButtonMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMenu.setText("MENÚ");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jButtonAleatorios.setBackground(new java.awt.Color(102, 0, 153));
        jButtonAleatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAleatorios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAleatorios.setText("ALEATORIOS");
        jButtonAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatoriosActionPerformed(evt);
            }
        });

        jSpinnerDia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSpinnerDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinnerAño.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSpinnerAño.setModel(new javax.swing.SpinnerNumberModel(2000, 1950, 2000, 1));

        jComboMes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNomb2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonMostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L3)
                    .addComponent(L6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerAño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNomb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNomb2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAlta)
                            .addComponent(jButtonBaja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMostrar)
                            .addComponent(jButtonModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMenu)
                            .addComponent(jButtonAleatorios))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        oCnx.mostrarPlomero(jTableRegistro);
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        String curp = this.jTextCurp.getText();
        String nombre1 = this.jTextNomb1.getText();
        String nombre2 = this.jTextNomb2.getText();
        String apPat = this.jTextApPaterno.getText();
        String apMat = this.jTextApMaterno.getText();
        int diaNP = Integer.parseInt(this.jSpinnerDia.getValue().toString());
        String mesNP = this.jComboMes.getSelectedItem().toString();
        int añoNP = Integer.parseInt(this.jSpinnerAño.getValue().toString());
        String correoElec = this.jTextCorreo.getText();

        oCnx.altaPlomero(curp, nombre1, nombre2, apPat, apMat, diaNP, mesNP, añoNP, correoElec);
        oCnx.mostrarPlomero(jTableRegistro);
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        String curp = this.jTextCurp.getText();
        oCnx.bajaPlomero(curp);
        oCnx.mostrarPlomero(jTableRegistro);
    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        String curp = this.jTextCurp.getText();
        String nombre1 = this.jTextNomb1.getText();
        String nombre2 = this.jTextNomb2.getText();
        String apPat = this.jTextApPaterno.getText();
        String apMat = this.jTextApMaterno.getText();
        int diaNP = Integer.parseInt(this.jSpinnerDia.getValue().toString());
        String mesNP = this.jComboMes.getSelectedItem().toString();
        int añoNP = Integer.parseInt(this.jSpinnerAño.getValue().toString());
        String correoElec = this.jTextCorreo.getText();

        oCnx.modificarPlomero(curp, nombre1, nombre2, apPat, apMat, diaNP, mesNP, añoNP, correoElec);
        oCnx.mostrarPlomero(jTableRegistro);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTableRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroMouseClicked
        if(evt.getClickCount() > 0){
            this.jTextCurp.setText(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 0).toString());
            this.jTextNomb1.setText(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 1).toString());
            this.jTextNomb2.setText(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 2).toString());
            this.jTextApPaterno.setText(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 3).toString());
            this.jTextApMaterno.setText(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 4).toString());
            this.jSpinnerDia.setValue(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 5));
            this.jComboMes.setSelectedItem(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(),6));
            this.jSpinnerAño.setValue(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 7));
            this.jTextCorreo.setText(this.jTableRegistro.getValueAt(this.jTableRegistro.getSelectedRow(), 8).toString());
        }
    }//GEN-LAST:event_jTableRegistroMouseClicked

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
        
    }//GEN-LAST:event_L1MouseClicked

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        //BOTON MENU
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatoriosActionPerformed
        // TODO add your handling code here:
        int x = random.nextInt(nombres.length);
        this.jTextCurp.setText(Integer.toString(random.nextInt(100)+100) + abc[random.nextInt(abc.length)] + abc[random.nextInt(abc.length)] + abc[random.nextInt(abc.length)]);
        this.jTextNomb1.setText(nombres[x]);
        this.jTextNomb2.setText(nombres[random.nextInt(nombres.length)]);
        this.jTextApPaterno.setText(Aps[random.nextInt(Aps.length)]);
        this.jTextApMaterno.setText(Aps[random.nextInt(Aps.length)]);
        this.jSpinnerDia.setValue(random.nextInt(30)+1);
        this.jComboMes.setSelectedIndex(random.nextInt(12)+1);
        this.jSpinnerAño.setValue(random.nextInt(51)+1950);
        this.jTextCorreo.setText(nombres[x] + abc[random.nextInt(abc.length)] + abc[random.nextInt(abc.length)] + abc[random.nextInt(abc.length)] + "@gmail.com");
    }//GEN-LAST:event_jButtonAleatoriosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plomero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plomero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plomero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plomero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plomero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton jButtonAleatorios;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JComboBox<String> jComboMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAño;
    private javax.swing.JSpinner jSpinnerDia;
    private javax.swing.JTable jTableRegistro;
    private javax.swing.JTextField jTextApMaterno;
    private javax.swing.JTextField jTextApPaterno;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextCurp;
    private javax.swing.JTextField jTextNomb1;
    private javax.swing.JTextField jTextNomb2;
    // End of variables declaration//GEN-END:variables
}
